packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@prisma/engines": true
  prisma: true
  unrs-resolver: true

catalog:
  typescript: 7.0.2

minimumReleaseAgeExclude:
  - "@types/react-dom@19.2.7"
